### ISSUE TITLE
项目介绍可不可以加图片展示啊

### ISSUE THREAD

**Issue by liaojiaao** [WPFDevelopersOrg/XNode#8]
看到这个项目介绍,没有直观的图片展示,没有图片就有点心痒难耐的

**Comment by githowe** [comment]
> 看到这个项目介绍,没有直观的图片展示,没有图片就有点心痒难耐的

我不是放了张图片么。详细的项目介绍正在写，写完会发布至我的[博客](http://www.gjiang.club/)上。
